### ISSUE TITLE
Write a tool to sort books according to Goodreads rating 

### ISSUE THREAD

**Issue by hackerkid** [hackerkid/Mind-Expanding-Books#102]
It would be awesome if you can write a commandline tool that will sort the books in each category according to Goodreads rating. The  tool should basically read from README.md and update it once the task is completed. You can use Goodreads API for achieving this. Let me know if you have any doubt :)

**Comment by dhinske** [comment]
I could contribute a cmd-line tool in java, if thats something you have in mind :)

**Comment by hackerkid** [comment]
@dhinske Yeah. I was looking for a command line tool. Looking forward to it :)

**Comment by AnshulMalik** [comment]
How about a bash script, java seems complicated, we need jre or jdk stuff

**Comment by hackerkid** [comment]
@AnshulMalik If you can write a bash script to do this feel free to write one and send a PR :)

**Comment by AnshulMalik** [comment]
How about python? Bash will be a bit complicated :P

**Comment by dhinske** [comment]
bash would be the most native solution. i can give it a shot

**Comment by hackerkid** [comment]
@AnshulMalik @dhinske Whatever works for you works for me :)

**Comment by hackerkid** [comment]
Fixed in #105
