### ISSUE TITLE
Way to verify whether the book is mind expanding or not

### ISSUE THREAD

**Issue by gauthamzz** [hackerkid/Mind-Expanding-Books#16]
There are so many books how do you know if it is mind expanding or not ?
There are so many great books and if we fill it with all it will be too big. Categories like fiction can become so big 
List doesnt explain how a particular books helps in expanding the mind . I

**Comment by hackerkid** [comment]
@gauthamzz Let's change the contributing guidelines. The pull request should list reasons on why the book is mind expanding.

**Comment by gauthamzz** [comment]
What if people explain in too many words and in a confusing way .
