### ISSUE TITLE
website: Add a navbar or menu bar that allows users to filter books category wise

### ISSUE THREAD

**Issue by hackerkid** [hackerkid/Mind-Expanding-Books#182]
Currently there is now way to filter books according to category. We should build a menubar/navbar that shows all categories and allows users to filter books accoridng to category.

See https://github.com/hackerkid/Mind-Expanding-Books/tree/master/app for details on setting up the development environment.

**Comment by HarisSpahija** [comment]
Hey @hackerkid , I would love to work on this! Can you let me know what I can do?

**Comment by hackerkid** [comment]
@HarisSpahija Sure. Basically you have to add a menu that has the list of all book categories. When users click on a category in the menu only the books from that category should be shown. 

![Screenshot from 2019-10-19 01-34-21](https://user-images.githubusercontent.com/7190633/67124962-5c650180-f211-11e9-8d0d-17a0051ea8cb.png)


Something like this for example. https://github.com/hackerkid/Mind-Expanding-Books/issues/185

**Comment by hackerkid** [comment]
Fixed in https://github.com/hackerkid/Mind-Expanding-Books/commit/1593c00620de287e47c014b5de0f1781ce83c2a8
