### ISSUE TITLE
website: Implement sorting of books functionality

### ISSUE THREAD

**Issue by hackerkid** [hackerkid/Mind-Expanding-Books#183]
Users should be able to sort books on basis of rating, year published, title etc. 

See https://github.com/hackerkid/Mind-Expanding-Books/tree/master/app to setup development environment

**Comment by galElmalah** [comment]
Hey, can you please assign this to me?
Also, where can I find the fields we want the books to be sorted by?

**Comment by hackerkid** [comment]
@galElmalah You can add sorting by year, alphabetic order and rating. 

See `app/src/data/books.json` for all the fields.

**Comment by galElmalah** [comment]
I think you can probably close this now 😄

**Comment by hackerkid** [comment]
Fixed in #241

**Comment by galElmalah** [comment]
@hackerkid NP! 😄
