### ISSUE TITLE
website: Improve the UI of book cards

### ISSUE THREAD

**Issue by hackerkid** [hackerkid/Mind-Expanding-Books#186]
The UI of book cards is not that great currently. Lot of improvements can be made in terms of how they look. For example how the category is displayed currently in the card is not pleasant and can be improved. Feel free to make any changes that you think improve the design of cards.

See https://github.com/hackerkid/Mind-Expanding-Books/tree/master/app  for details on setting up the development environment.

**Comment by lielfr** [comment]
Hi,
I'd like to work on this one if possible :smile:

**Comment by hackerkid** [comment]
@lielfr Sure. Go ahead :)

**Comment by lielfr** [comment]
@hackerkid What do you think about this?
**Individual cards**
![image](https://user-images.githubusercontent.com/360928/67110045-85b66b00-f1da-11e9-8e38-5dda739ce72c.png)

**Grid**
![image](https://user-images.githubusercontent.com/360928/67110106-a2eb3980-f1da-11e9-9d36-281170446d24.png)

**Comment by hackerkid** [comment]
@lielfr This looks like an imorovment. Create a PR?

**Comment by mridul-arora** [comment]
Could you close the issue so that it doesn't create more confusions

**Comment by hackerkid** [comment]
hmm. I think a lot more improvements can be made in UI of books cards. So going to leave this issue open.

**Comment by Prathamesh404** [comment]
Hello,
So I have seen all the issues raised. 
1. Need categorisation. Consider a Wikipedia articles. The reference for categories can be a great help to scroll down to specific category.
2. The book cards can have link to Amazon for buying.
3. Every Book can have a gist about what knowledge it offers.
4. UI book cards look good, but I guess every book have same cover  page as of now, is there any image copyright issue to not update every book cover
So right now the website functions as a static website with infinite scroll. 
What are the plans for further development?

**Comment by hackerkid** [comment]
> Need categorisation. Consider a Wikipedia articles. The reference for categories can be a great help to scroll down to specific category.

Yes. There is an issue open for this. https://github.com/hackerkid/Mind-Expanding-Books/issues/182

> he book cards can have link to Amazon for buying.

This is a good idea. But I would prioratize this after other major issues are fixed.

> Every Book can have a gist about what knowledge it offers.

Good suggestion I think this can be extracted form the GoodReads API. 

> UI book cards look good, but I guess every book have same cover page as of now, is there any image copyright issue to not update every book cover

I have not yet updated the json files with the appropriate links to the book images. The script for that is  done and present in the utils directory I think.


> What are the plans for further development?

I dont currently have time to work on the website at the moment. But I appreciate PRs from folks who are interested in making the website :)

**Comment by hackerkid** [comment]
@Prathamesh404 FYI ^^^. Forgot to tag in the previous comment.

**Comment by hackerkid** [comment]
I have made a lot of changes to the card component recently. 

![Screenshot from 2020-08-24 00-01-01](https://user-images.githubusercontent.com/7190633/90985959-ef429b00-e59c-11ea-9315-b458cc5d8ad1.png)

It still can do a lot more improvement but I don't necessarily think we need an issue open for that. Closing this.
