### ISSUE TITLE
website: Implement functionality to mark books as "to read" using localstorage

### ISSUE THREAD

**Issue by hackerkid** [hackerkid/Mind-Expanding-Books#187]
Users should be able to mark books as to read. The data can be stored in local stoarge. There should be also an option to see all the books that users marked as to read. Future project would be to sync the data with a backend but that is beyond the scope of this issue.

See https://github.com/hackerkid/Mind-Expanding-Books/tree/master/app  for details on setting up the development environment.

**Comment by CarlsJr4** [comment]
Hi! I'd love to work on this issue. I've worked with Gatsby and localStorage before. I'll see what I can do.

**Comment by hackerkid** [comment]
Great. Go ahead :)

**Comment by hackerkid** [comment]
This was fixed in https://github.com/hackerkid/Mind-Expanding-Books/pull/252
