### ISSUE TITLE
define "Mind Expanding Books"

### ISSUE THREAD

**Issue by satyanash** [hackerkid/Mind-Expanding-Books#201]
Given that _Books that will blow your mind_ is very subjective, it would help to define what does a book have to do, to be considered "Mind Expanding".

Given the current selection, it seems that any book that is well known and has a goodreads rating ~4.0 makes the list. If it's difficult to come up with anything else, shouldn't we at least codify this part?

**Comment by hackerkid** [comment]
@satyanash Interesting. A book greater than 4.0 is a great indicator. We can maybe add a testcase that makes sure that the books rating has to be atleast 4. Maybe we can check Amazon.com review score as well? If you are thinking of working on this issue this is what I would do.
* Write a Unittest that makes sure that the book added in the last commit is in proper format. Format being
```
| Name | Author | Goodreads Rating | Year Published |
```
* Add a check that make sures that the rating is >= 4.

* If you have more time on this add a function to get the Amazon.com rating of the book and make sure that its above 4. Not sure how to do this really. But I think you can get the ISBN no from Goodreads API and use that to get rating from Amazon and other sites probably.

**Comment by b00sher** [comment]
Agree with @satyanash point, it seems like a list of _just_ books with a good rating, without any comments or thoughts. Have you (@hackerkid) read all of them? Why would one book is better than another? Because of the score? 

Don't worth that much attention, as for me.

**Comment by hackerkid** [comment]
> Agree with satyanash point, it seems like a list of just books with a good rating, without any comments or thoughts.

Yeah. Actually when the person creates a PR for adding the book, they are asked how many times they have read the book as well as the reasoning for adding the book to the list. I normally only merge PRs that has strong reasoning for adding the book to the list. Ofourse if you can come up with a way to enforce this rules through code feel free to do so. Also if you don't like some books that are in the list feel free to create PRs with your reasoning to remove them.

**Comment by b00sher** [comment]
I think this repo is too opinion-based to has a name as such. Here is hierarchy, as I get it: 

You (@hackerkid) accept book (PR) that:

0. [book] Has been read by someone, who also has to explain reasons why they thinks it is "mind-expanding". (opinion-based, but includes reasons/thoughts)
1. [PR] Has _strong_, in your opinion, reasoning for adding the book.
2. [book] Has a good rating* (rating is also opinion based, but it is fine as long as it includes review or reasons for an estimation)

*the column with rating in book-lists makes me believe that it matters.

Current repo description stays: "📚 Books that will blow your mind". As far as I know myself, I'm sure that my mind wouldn't blow up for at least one book from the "Humor" section. (this was a joke, there is only one book in that section, get it?)

As I suppose changing the repository name isn't an option, can you please change the description _and_  express somewhere in the readme how you understand a purpose of this repo (`Curated list of mind expanding books.`, say from where books come from, why would they "blow someone's mind").

**Comment by hackerkid** [comment]
@b00sher That is a reasonable suggestion. Will make the necessary changes soon.

**Comment by alivapriyadarshini5** [comment]
added a theater book #318

**Comment by hackerkid** [comment]
I have made many changes since the last discussion.

The description of the repo is now

> Looking to find a book an interesting book to read but don't know where to start? You are in the right place!

I have also updated the CONTRIBUTING guidelines to include more details on accepting criteria.

https://github.com/hackerkid/Mind-Expanding-Books/blob/master/CONTRIBUTING.md

So closing the issue for now. Feel free to reopen.
