### ISSUE TITLE
Common Book Image

### ISSUE THREAD

**Issue by samishakhurana** [hackerkid/Mind-Expanding-Books#213]
Hi, so I wanted to know is there any particular reason for using a common book image ( " Shoe Dog: A memoir by the creator of Nike " ) for all the books.
I understand that finding cover for every book is a bit cumbersome since there is already a big list present by now, but the same cover looks a bit weird.
I would like to suggest two ways to fix this - 
1) A more generic image can be used
2) Design of book card could be changed to more attractive visual (where image is not a very prominent part) and moving forward book image can be made a mandatory field

**Comment by hackerkid** [comment]
My plan was to fetch the cover image of the book from Goodreads API.

I think I have made changes to the script to do this as well. But the last time I ran the script it took way too much time to run.

https://github.com/hackerkid/Mind-Expanding-Books/blob/master/utils/gooodreads.py

If you are interested in contributing to the issue you can play around with the script and get the details of all the books in JSON format.

The JSON data is then used by the app/ to create HTML pages.

**Comment by hackerkid** [comment]
The [website](https://books.vishnuks.com) now has the correct image for most books. I need to get the book image for the left out books using some other API.
