### ISSUE TITLE
Minor UI improvements for better User Experience

### ISSUE THREAD

**Issue by samishakhurana** [hackerkid/Mind-Expanding-Books#214]
I would like to highlight some minor UI issues - 
1) There can be a default cover page for books for which images are not present, currently it comes as an empty box.
2) Book cards are overlapping long category names.
![Screen Shot 2020-08-31 at 9 23 51 PM](https://user-images.githubusercontent.com/32064975/91740439-ed965a00-ebd0-11ea-95ec-8c431845295e.png)
![Screen Shot 2020-08-31 at 9 23 57 PM](https://user-images.githubusercontent.com/32064975/91740475-f6872b80-ebd0-11ea-83a2-8718618be210.png)

**Comment by samishakhurana** [comment]
If you feel like these changes would help, I would like to work on them.
Thanks ~

**Comment by hackerkid** [comment]
Cool. Feel free to work on the 2nd issue. I  have in my todo list to fetch book covers for the ones that are missing at the moment from another API. Also, the categories section on the left side is not responsive at the moment. If I open the website in a mobile it won't resize properly. I think ideally when the website is opened the categories should come first and then the books should be shown. Let me know if you have any further queries.

**Comment by samishakhurana** [comment]
Hello @hackerkid , I am opening a PR for the partial fix of this issue.
It would be a little help if you can add hacktoberfest label to this. :)
Thanks ~

**Comment by hackerkid** [comment]
I am closing since a lot of PRs have been created in this category.
