### ISSUE TITLE
Add instructions on how to get the site going locally

### ISSUE THREAD

**Issue by thedudio** [hackerkid/Mind-Expanding-Books#229]
Hi, im new to open source, but not to webdesign and I think the website has a lot of potential to look much better.
The problem is, I cannot find any instructions on how to setup the site locally. I never used gatsby and I'm not sure, if this is the only thing I need to get started working on the style of the site efficiently.
Maybe this is a stupid question, let me know. :)

**Comment by redxzeta** [comment]
1.   `cd app`

1.  `npm i`

1.  `npm start`

**Comment by hackerkid** [comment]
Yeah. Try the instructions above. I have also added it now in README of the app/

https://github.com/hackerkid/Mind-Expanding-Books/tree/master/app
