### ISSUE TITLE
Refactor the Layout

### ISSUE THREAD

**Issue by BlameFelix** [hackerkid/Mind-Expanding-Books#233]
Hey, I'd like to contribute for the hacktoberfest.

I could refactor the layout to one from [ant design](ant.design) if you want to use more of their stuff later on?

I'd pick one of [these](https://ant.design/components/layout/), I suggest the sider one as its pretty similar to the one already existing.
Let me know what you think

**Comment by hackerkid** [comment]
@BlameFelix  I was also considering Ant design when I started working on the website. It's really cool :)

But let's stick for React Bootstrap for now. There are a lot of PRs being made so refactoring to Ant would create a lot of merge conflicts.
