### ISSUE TITLE
[UI BUG] Goodreads image is covering the book card

### ISSUE THREAD

**Issue by xevenheaven** [hackerkid/Mind-Expanding-Books#244]
While exploring the website, I noticed that the Goodreads image is covering most of the book card:

![image](https://user-images.githubusercontent.com/6725396/95723483-c8a10680-0ca7-11eb-8b77-03a8a19444e5.png)

**Comment by hackerkid** [comment]
I think its fixed in production now. Can you hard reload and see.

**Comment by xevenheaven** [comment]
@hackerkid yup the Goodreads image is gone now. 😄 

I see that you've reverted the commit for Goodreads [here](https://github.com/hackerkid/Mind-Expanding-Books/commit/f4446aff0762e5b0bdc1a448a2356c7d4ccb9770). I've actually made some style fixes and updates to the book card, inclusive of the Goodreads image - PR https://github.com/hackerkid/Mind-Expanding-Books/pull/245 just created. Perhaps you could take a look and see if this is what you want?
