### ISSUE TITLE
Use another API for fetching book covers when Goodreads API don't have a valid book cover

### ISSUE THREAD

**Issue by hackerkid** [hackerkid/Mind-Expanding-Books#273]
If you open the website you can see that a lot of books have book covers missing. 

eg https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png

The reason behind is that Goodreads don't have the licensing rights to distribute the cover photo of the book using the API (or something like that).

It's easy to see whether the book cover URL is valid or not since Goodreads return the same image URL for books without a valid cover photo.

So your task is to use another API for fetching the book cover when Goodreads return an invalid book cover.

`utils` directory has the scripts that is used for generating `books.json`

Look at the README.md file in the `utils` directory for more details.

**Comment by JacksonIsaac** [comment]
Would like to work on this :) Setting up the environment now

**Comment by hackerkid** [comment]
@JacksonIsaac Awesome. Thanks!

**Comment by JacksonIsaac** [comment]
@hackerkid, looks like lot of packages in requirements.txt are not on pypi (or either having lower of higher version numbers). Is this intentional ?

**Comment by hackerkid** [comment]
@JacksonIsaac We don't use any packages that are not in pypi. I added some instructions on setting up the packages just now. Can you give it a try? 
https://github.com/hackerkid/Mind-Expanding-Books/tree/master/utils#install-packages-for-script

The python on my system has `3.8` in case it doesn't work with your version.

**Comment by JacksonIsaac** [comment]
@hackerkid These were the steps I followed, yes. I am using python 3.7 on macOS

**Comment by hackerkid** [comment]
@JacksonIsaac What error are you getting?

**Comment by JacksonIsaac** [comment]
pip install -r requirements.txt
Collecting appdirs==1.4.3
  Using cached appdirs-1.4.3-py2.py3-none-any.whl (12 kB)
ERROR: Could not find a version that satisfies the requirement apturl==0.5.2 (from -r requirements.txt (line 2)) (from versions: none)
ERROR: No matching distribution found for apturl==0.5.2 (from -r requirements.txt (line 2))

**Comment by hackerkid** [comment]
@JacksonIsaac Okay. I think the issue is that we had an outdated requirements.txt file in the root folder. The requirments.txt file you need to use is present inside `utils` directory. I have removed the extra requirments.txt file from root and pushed to master. Can you give it another try?
