### ISSUE TITLE
Use another API for fetching the book description when Goodreads API return empty description

### ISSUE THREAD

**Issue by hackerkid** [hackerkid/Mind-Expanding-Books#274]
If you go through `app/src/data/books.json/` you can see that a lot of the books have the description empty. We are not displaying the books without a description in the website.

Your task is to use another API for fetching the book description when Goodreads return an empty description.

The scripts that are used for generating the `books.json` file lives in `utils` directory

Go through the README file in `utils` directory for more details on running the script.

**Comment by ariesgun** [comment]
If no one is working on this, i want to take this.

**Comment by hackerkid** [comment]
@ariesgun Feel free to work on the issue :)

**Comment by hackerkid** [comment]
Fixed in #316
