### ISSUE TITLE
Add a book that blowed your mind | hacktoberfest

### ISSUE THREAD

**Issue by hackerkid** [hackerkid/Mind-Expanding-Books#29]
This repository contains books that blowed the mind of a lot of people. f you know of any such :book:  that is not in the list then please make a PR. Thanks for being awesome :sunglasses: . Happy Hacktoberfest. :tada:

**Comment by q3qt** [comment]
@hackerkid I want to contribute a book.

**Comment by ivydigitalstorm** [comment]
@hackerkid i would like to contribute a book too :) #hacktoberfest

**Comment by BNVision** [comment]
Hey @hackerkid I want to contribute a book

**Comment by hackerkid** [comment]
Thank you all for contributing. :tada:
