### ISSUE TITLE
Incremental builds

### ISSUE THREAD

**Issue by DBozhinovski** [hackerkid/Mind-Expanding-Books#337]
Recently, Netlify added a free plugin for enabling incremental builds for Gatsby sites. On the ones I've worked on, I noticed significant speed-ups in build times, so it might be a good idea to add that too. I'd be okay with handling the config part myself, but  the Netlify plugin also needs to be enabled.

**Comment by hackerkid** [comment]
@DBozhinovski Sounds great. Feel free to create a PR. Is this the plugin that I should enable?
![Screenshot from 2020-10-28 23-13-40](https://user-images.githubusercontent.com/7190633/97475443-484ef680-1973-11eb-8c37-cae90830c9d0.png)

**Comment by DBozhinovski** [comment]
Yup, that's the one :+1:

**Comment by hackerkid** [comment]
Done :)
