### ISSUE TITLE
Book title doesn't match the picture of book shown or the information given

### ISSUE THREAD

**Issue by Shweta200126** [hackerkid/Mind-Expanding-Books#371]
![image](https://user-images.githubusercontent.com/72426535/120078628-f10e3180-c0cd-11eb-8fab-db2c3d6ab4fa.png)

This is in context with the book **The Discoverers by Daniel J. Boorstin 2012** in history section but it shows Aristotle and Dante's book with its description but the links are correct. I refreshed the page many times but it doesn't change, its a problem.

**Comment by hackerkid** [comment]
@Shweta200126 Yes. It's defintely a bug that I have seen before. Can you try debugging it if you have some spare time?

**Comment by Shweta200126** [comment]
@hackerkid ya sure, I'll see it in the night/morning.
