### ISSUE TITLE
Adding Self-help Section

### ISSUE THREAD

**Issue by Snimer** [hackerkid/Mind-Expanding-Books#449]
I think we should add a self-help category too. There are many books which can be added in this. Many of them are already added in philoshy and psychology category but many them are more of a self help book than a pshycology book.

**Comment by iArmanKarimi** [comment]
I agree. self-help books are kind of part of the psychology criteria. so they can be added as a branch of psychology.

**Comment by iArmanKarimi** [comment]
I agree. self-help books are kind of part of the psychology criteria. so they can be added as a branch of psychology.

**Comment by robin00007** [comment]
That is so true I also just landed just finding the one. It should be added .

**Comment by hackerkid** [comment]
Feel free to create a PR. I am going to close this for now.
