### ISSUE TITLE
[Bug] when clicking in goodreads button it should be open in another page.

### ISSUE THREAD

**Issue by love-sonkar** [hackerkid/Mind-Expanding-Books#465]
when you try to read book by clicking goodread button the link should be open in new tab like other buttons.

if you click in amazon button the link is open in another tab but when you click in goodread button the link is not open in new tab this is a bug please fix this isseu for better UI experience.

https://github.com/hackerkid/Mind-Expanding-Books/assets/82786865/f79539d3-97e6-4c7b-b62f-0bfa3eb969e5

**Comment by var-rishabh** [comment]
Hey @love-sonkar can you assign this issue to me?
I can fix this easily.

**Comment by love-sonkar** [comment]
this issue is merged bro you can check another issue @var-rishabh
