### ISSUE TITLE
Add missing author names to the books

### ISSUE THREAD

**Issue by hackerkid** [hackerkid/Mind-Expanding-Books#49]
The author name of some of the books are missing. Add the author name for them.

**Comment by minibhati93** [comment]
Can I help you with this?

**Comment by hackerkid** [comment]
Yeah Sure. I see you are already making changes. Thanks for helping out.

**Comment by minibhati93** [comment]
Pleasure. Apologies for messing up the commits, though.

**Comment by ivydigitalstorm** [comment]
hi @hackerkid mind if I add one more author?

**Comment by hackerkid** [comment]
@ivydigitalstorm Thans for the PR :tada:

**Comment by hackerkid** [comment]
Fixed in multiple commits (https://github.com/hackerkid/Mind-Expanding-Books/commit/b9b78fa16c0f22df61f0f8521150907a9c8510d5, https://github.com/hackerkid/Mind-Expanding-Books/commit/b45080ecc030dfad596361e82a6d03476bca42a3)

Thanks @ivydigitalstorm @minibhati93
