### ISSUE TITLE
Order books sensibly

### ISSUE THREAD

**Issue by dakshshah96** [hackerkid/Mind-Expanding-Books#91]
Currently, the books in each category are listed in a random order with no real sense of organization.

I think it'd be better if the books were ordered in a particular manner. Few ideas for selecting the criteria for ordering books:
* Alphabetically
* Average Goodreads rating
* First publishing date

**Comment by dakshshah96** [comment]
@hackerkid I think the [Goodreads API](https://www.goodreads.com/api) will be very helpful here to generate a list of all books with their ratings. Let me see what I can find on that.

Yes, the publishing date can be added to the title. I can start working on that if that's what we want to do. 👍

**Comment by hackerkid** [comment]
@dakshshah96 I will give more importance in sorting the list according to the Goodreads API. You can also display the Goodreads rating of the book. I think when you do this you can also add date of publishing to the book as it would be just a few extra lines of code. We will run the scripts every couple of months.

**Comment by geritol** [comment]
I starting to write python script for this!

**Comment by hackerkid** [comment]
@geritol  Awesome. Looking forward to it.

**Comment by geritol** [comment]
https://github.com/geritol/Mind-Expanding-Books/
Ordering by title and author ready (check example files).
(The functionality is not refactored to a command line tool yet)
Will take a look on the ratings tomorrow it think.

**Comment by hackerkid** [comment]
@geritol Nice :)

**Comment by geritol** [comment]
@hackerkid Now I am retrieving the publishing year, original language, average rating a page count from the API. 
The question here is, should we show some of these in the .md file?
If so what would you propose for the new 'look' of a line containing a book?

**Comment by hackerkid** [comment]
@geritol  I am thinking we can convert the current format to that of a table.

|Name|Author|Goodreads Rating|Year Published|
|-------|---------|-------------------------|--------------------|
|Zero to One| Peter Thiel|[4.17](https://www.goodreads.com/book/show/18050143-zero-to-one)|2014|
|Hackers and Painters|Paul Graham|[4.06](https://www.goodreads.com/book/show/41793.Hackers_Painters)|2004|

Do you think you do something like this easily?

**Comment by hackerkid** [comment]
@geritol  I am thinking we can convert the current format to that of a table.

|Name|Author|Goodreads Rating|Year Published|
|-------|---------|-------------------------|--------------------|
|Zero to One| Peter Thiel|[4.17](https://www.goodreads.com/book/show/18050143-zero-to-one)|2014|
|Hackers and Painters|Paul Graham|[4.06](https://www.goodreads.com/book/show/41793.Hackers_Painters)|2004|

Do you think you do something like this easily?

**Comment by geritol** [comment]
can do for sure!
the only thing, that maybe in the source code the separators won't be well aligned. Put probably that can also be solved. Will try to achieve this today.

**Comment by geritol** [comment]
[by-author.md.zip](https://github.com/hackerkid/Mind-Expanding-Books/files/1345170/by-author.md.zip)
@hackerkid Seems not all the rows have _by_ before the author name.
This confuses my parser.
Could you fix this, please in the meantime?

You should look rows with odd values in the author column.


Thanks!

**Comment by geritol** [comment]
basically ready (check out: https://github.com/geritol/Mind-Expanding-Books/blob/master/README-NEW.MD)
some smaller stuff still left

**Comment by hackerkid** [comment]
This looks awesome and would turn this list much useful!

**Comment by hackerkid** [comment]
@geritol  I fixed syntax issues in https://github.com/hackerkid/Mind-Expanding-Books/commit/5598f3856a39f5d577eb32af4e4a220ea58befcf. you parser should work fine now :)

**Comment by geritol** [comment]
Cool, I think you left this one in:
* [Darwin's Dangerous Idea](https://www.goodreads.com/book/show/2068.Darwin_s_Dangerous_Idea) Daniel C. Dennett

**Comment by geritol** [comment]
Basically ready, If you what to take a look check my fork.
PR coming in tomorrow :)

**Comment by hackerkid** [comment]
@geritol Good catch. Fixed in c030a050ae0f9c8bd9120974fc63b4082556fb44

**Comment by geritol** [comment]
see pr #105 :)

**Comment by hackerkid** [comment]
Fixed in #105
